### ISSUE TITLE
Days as number

### ISSUE THREAD

**Issue by NotSoMik** [valddd/district#1]
Hello (about the anti alt system) I saw you put Days: String [here](https://github.com/valddd/district/blob/main/schemas/anti-alt.js#L10) but it wouldnt be better to use Days: Number? Since you also used interaction.options.getNumber in your command

**Comment by valddd** [comment]
Hello mate, I sincerely don’t know about the code I just clone it for a host.
I want to tell you i love you mate and thanks for you’re time, really appreciate it! And sorry :(
(If you want to feedback the real dev is https://github.com/Siris2314/NecroAtomicBot)

**Comment by NotSoMik** [comment]
Oh sure thanks for you reply
